export const NavData = [
  {
    id: 1,
    title: "Find Jobs",
    link: "/",
    slug: "home",
  },
  {
    id: 2,
    title: "Top Companies",
    link: "/top-companies",
    slug: "top-companies",
  },
  {
    id: 3,
    title: "Job Tracker",
    link: "/job-tracker",
    slug: "job-tracker",
  },
  {
    id: 4,
    title: "My Calendar",
    link: "/my-calendar",
    slug: "my-calendar",
  },
  {
    id: 5,
    title: "Documents",
    link: "/documents",
    slug: "documents",
  },
  {
    id: 6,
    title: "Messages",
    link: "/messages",
    slug: "messages",
  },
  {
    id: 7,
    title: "Notifications",
    link: "/notifications",
    slug: "notifications",
  },
];

export const locationData = [
  {
    label: "1st Location",
    key: "0",
  },
  {
    label: "2nd Location",
    key: "1",
  },
  {
    label: "3rd Location",
    key: "3",
  },
];

export const jobTypeData = [
  {
    label: "Full Time",
    key: "0",
  },
  {
    label: "Part Time",
    key: "1",
  },
  {
    label: "Contract",
    key: "2",
  },
  {
    label: "Internship",
    key: "3",
  },
];

export const featureJobCardData = [
  {
    id: 1,
    promoted: true,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 2,
    promoted: true,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: true,
  },
  {
    id: 3,
    promoted: true,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 4,
    promoted: true,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 5,
    promoted: true,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
];

export const recommededJobCardData = [
  {
    id: 1,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 2,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: true,
  },
  {
    id: 3,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 4,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 5,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 6,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 7,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: true,
  },
  {
    id: 8,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 9,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 10,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
];
export const latestJobCardData = [
  {
    id: 1,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 2,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: true,
  },
  {
    id: 3,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 4,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 5,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 6,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 7,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: true,
  },
  {
    id: 8,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 9,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
  {
    id: 10,
    promoted: false,
    title: "UI/UX Designer",
    company: "Teams",
    location: "Seattle, USA (Remote)",
    postedAt: "1 day ago",
    applicants: 22,
    applyText: "Apply Now",
    bookmarked: false,
  },
];


